### ISSUE TITLE
RDMD Compatibility Mode

### ISSUE THREAD

**Issue by rafegoldberg** [readmeio/api-explorer#668]
Per the discussion [here](https://github.com/readmeio/api-explorer/pull/660#issuecomment-621908636), we'd like to add a mode to the RDMD engine that enables certain, otherwise non-compliant behaviors in the name of backwards compatibility! Here's a quick list of included features off the top of my head:

- [x] Block components in tables (#660)
- [x] Render magic headings as `<h1>`s (#820)
- [x] Script JS execution in Custom HTML blocks (#820) [<img width=16px align=center src=https://user-images.githubusercontent.com/886627/84447734-b598ff80-abfd-11ea-8342-21aeaa878b1b.png>](https://stackoverflow.com/a/35616264/1341949 "Executing script tags in dangerously set HTML")
